---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: no_proxy
    run_list:
      - recipe[proxy::default]
    verifier:
      inspec_tests:
        - test/integration/no_proxy
    attributes:
  - name: with_proxy
    run_list:
      - recipe[proxy::default]
    verifier:
      inspec_tests:
        - test/integration/with_proxy
    attributes:
      proxy:
        http: http://proxy.example.com/
        https: http://sproxy.example.com/
        'no': localhost:example.com

